### ISSUE TITLE
commit->getTree error

### ISSUE THREAD

**Issue by msierks** [libgit2/php-git#16]
calling $commit->getTree on a valid commit object results in the following error.

Fatal error: Git\Commit::getTree(): specified tree not found. 

Yet when I dump the commit object I see

 ["tree":protected]=> string(40) "765cfd1f3d91010d5e45d2af3a40a6a7eb4f7378"

**Comment by chobie** [comment]
probably it failed to lookup tree object.
can you tell me which repository could not obtain the tree object if it's possible?
also PHP, libgit2 and php-git version it's helpful.

**Comment by msierks** [comment]
Well the repository is a temp one I created with a single commit. It contains one file "README".
PHP 5.3.8
libgit2 0.15.0
php-git 20111015
Also this is running on x86_64 Linux.

**Comment by chobie** [comment]
thank you for reporting the issue. i apologize this suck mistook.
i've just fixed it. please check latest devlop branch.
https://github.com/libgit2/php-git/commit/c3e019cd78b301fdbb3fd9d0c900f4e87786f6cf

once i modified some C99 codes to C89 for windows support. so probably it might be appeared some bugs.

**Comment by msierks** [comment]
Thank you, I will be integrating git into my website slowly so expect more bug reports from me.
