### ISSUE TITLE
How to determine if repository is empty

### ISSUE THREAD

**Issue by msierks** [libgit2/php-git#17]
Is there a way to easily determine if a repository is empty with this library ?

**Comment by chobie** [comment]
how about this?

``` php
<?php
$repo = new Git\Repository("path_to/.git");
if ($repo->empty()) {
    echo "repository is empty";
} else {
    echo "repository has some commits";
}
```

**Comment by msierks** [comment]
I guess the easiest way would be to call getReferences and if none existed then it is empty ???

**Comment by msierks** [comment]
Ah that is perfect, I didn't know that function existed. I guess the documentation is a little incomplete.
