### ISSUE TITLE
Docs links are broken

### ISSUE THREAD

**Issue by cweagans** [libgit2/php-git#19]
The links to the project documentation in the README do not point to anything useful. Chobie's website is offline (I just get the default "It works!" page from Apache), and the wiki on Chobie's repository is disabled for some reason.

Documentation for this project would be fantastic. I'm planning on building a Drupal 7 based clone of Github and would really love to use this library.

Thanks!

**Comment by chobie** [comment]
thank you follow up it.

i'd uploaded current docs to gh-pages (http://libgit2.github.com/php-git/). probably it has little bit out of dated docs.
please read implementation and some samples.

https://github.com/chobie/githq

you guys really love drupal7. probably php-git possible to implement it easier i think.
but some low-level features (blame, commit diff, pull request, obtaining each files latest commit log, clone via ssh or http), you should use `git` command directly as it's easiest way to implement.
