### ISSUE TITLE
tree->getEntryByName

### ISSUE THREAD

**Issue by msierks** [libgit2/php-git#24]
I get the following error when calling $tree->getEntryByName().

"symbol lookup error: /usr/lib/php/modules/git2.so: undefined symbol: git_oid_tostr"

Can you please fix ?

**Comment by chobie** [comment]
Hi, I'll do in this weekend.
for now, can you try to use old libgit2 release?

**Comment by chobie** [comment]
@msierks which libgit2 version did you use? All tests passed with latest libgit2.

**Comment by msierks** [comment]
v0.16.0 or latest dev build ?

**Comment by chobie** [comment]
oh, I see. please use latest dev build as libgit2 has grown very fast :sparkles:
