### ISSUE TITLE
Error on 'make'

### ISSUE THREAD

**Issue by stovak** [libgit2/php-git#30]
/tmp/php-git/repository.c:237:13: error: use of undeclared identifier 'GIT_SUCCESS'
        if (ret == GIT_SUCCESS) {
                   ^
/tmp/php-git/repository.c:313:124: error: use of undeclared identifier 'GIT_SUCCESS'
        if (git_repository_discover(path_buffer,path_size,(const char *)start_path,(int)across_fs, (const char *)ceiling_dirs) == GIT_SUCCESS) {
                                                                                                                                  ^
/tmp/php-git/repository.c:341:36: error: use of undeclared identifier 'GIT_SUCCESS'
        if (git_oid_fromstr(&id, hash) != GIT_SUCCESS) {
                                          ^
/tmp/php-git/repository.c:377:47: error: use of undeclared identifier 'GIT_SUCCESS'
        if (git_oid_fromstrn(&id, hash, hash_len) != GIT_SUCCESS) {
                                                     ^

SYSTEM: macOS X MAMP and PHP 5.4

**Comment by chobie** [comment]
please see. https://github.com/libgit2/php-git/issues/29

I'l fix this issue on this month (i have summer vacation and my wife will go to trip this week. Yay, hacking time.)

**Comment by chobie** [comment]
this issue solved current development branch. closing issue.
