### ISSUE TITLE
how can I create a new branch?

### ISSUE THREAD

**Issue by iannil** [libgit2/php-git#36]
Hi , I need to create a new branch like fork on github with php , is there any api can solve it?thx

**Comment by chobie** [comment]
I haven't implemented that API. I'll add it later

http://libgit2.github.com/libgit2/#HEAD/group/reference/git_reference_create_oid

also, this documents are useful.
http://ftp.newartisans.com/pub/git.from.bottom.up.pdf

**Comment by iannil** [comment]
ok , thans for your reply and php-git is very helpful and usefull.
i will pay attention for this api.

**Comment by chobie** [comment]
hey @zhurong I've added the API. please create a ticket if you found some required API.

**Comment by iannil** [comment]
hi, @chobie ,thanks for adding the API so fast and I will try it in near future.

**Comment by iannil** [comment]
hi , @chobie , thanks very much for your help first.
Git2\Reference::create is useful and works well now , and how to checkout the branch?

**Comment by chobie** [comment]
did you mean `checkout specified commit into working directory`? also that API doesn't implement yet.
I'll add checkout API soon.

**Comment by iannil** [comment]
ok and I am waiting for it.

**Comment by chobie** [comment]
@zhurong sorry, that API still experimental. you should execute `git checkout` with shell.

**Comment by iannil** [comment]
Did you mean that API is experimental in library named libgit2?

**Comment by chobie** [comment]
http://libgit2.github.com/libgit2/#HEAD/group/checkout/git_checkout_tree

specifically, there is `git_checkout_tree` API in libgit2. and it seems work in progress.
so I'd like to add this API into phpgit when libgit2 tagged next version.

**Comment by iannil** [comment]
Oh,I'll keep attention with it and maybe I should execute checkout with shell until libgit2 tagged next version.
Thanks for your help again.Good night at last :-)
