### ISSUE TITLE
Is further development stopped?

### ISSUE THREAD

**Issue by kingkorf** [libgit2/php-git#50]
Hi all,

For some time I'm tryin' to use this extension in a little project of mine. I like the functionality so far and really appreciate the work you guys did. 

But if i'm not mistaking the project is dead for about 7 months now, and there is still pretty much work to be done to fully couple libgit2. I'll try to do some coding myself and I hope there's gonna be some activity here again!

Cheers!

**Comment by chobie** [comment]
Actually, I stopped development php-git about 7 months. there are some reasons:
- my work is very hard in these few years.
- I have many php extensions to maintain (sundown, uv, libgit2, protocolbuffers ...etc). 
  specifically, libgit2 sometimes changes their api (I know this is needed for library). thinking OOP interface is one of tough work. so i'll add simple wrapping functions if i have time.
  I'll do php-git work when I finish some OSS work. (currently I work for protocolbuffers).
- Honestly, wrapping libgit2 is very tough for oneself. i need someone to help development.

anyway, patches and pull request are welcome :octocat:

**Comment by kingkorf** [comment]
Thanks for your quick response! I'll try to look at it myself although I do not have much experience with C or PHP extensions. I do though have a lot of experience in general programming, so I should get my hand around this pretty quick.
- Can you point me to a good tutorial on the subject of C and PHP extensions?
- Do you have suggestions where to start coding in this extension?

Thanks in advance, and I hope I can help out a little bit!

**Comment by chobie** [comment]
@kingkorf I recommend this book
- Extending and Embedding PHP
  http://www.amazon.com/dp/067232704X

you can also read the book with safari books online.
- pro git book
  http://git-scm.com/book

also you should read pro git book. 
- libgit2 api reference
  http://libgit2.github.com/libgit2/#HEAD

> Do you have suggestions where to start coding in this extension?
> for now, play with php-git. modify some codes and build. and do `make test`.

Honestly, contributing php-git is not a good start as it requires many knowledges (building php, low level git...) and my code is messy.

probably, you need a couple of month to learn about php extension. keep hacking.

**Comment by opensaurusrex** [comment]
Hi, I would like to help out if I can. I am very interested in this extension.

**Comment by kingkorf** [comment]
I myself am struggling with the patch output from diffs between commits. For now I just copied the diff function from repository.c and changed some stuff, and that is working for now by the way. I would like to do this in a better fashion. I'll send a pull request this week so you guys can look at it. 

I further found some small bugs in the code which I will post here too.

**Comment by chobie** [comment]
@kingkorf sounds good. You've continued PHP internal study.

btw, have you seen https://github.com/libgit2/php-git/pull/53#issuecomment-31862697 ? 
I'm preparing non OOP branch. this change impact is very big. please watch current development status.

**Comment by chobie** [comment]
@deth4uall probably I'll push new branch in a few days. could you play with new one when pushed?
it's not OOP style but It makes easy to keep development.

**Comment by opensaurusrex** [comment]
Yeah I will. Just let me know when it's available. I can probably wrap a class around the functions to utilize the non-OOP characteristics in an OOP manner. Will they use at least references?

**Comment by chobie** [comment]
for now, I'm working `functions` branch (https://github.com/libgit2/php-git/tree/functions) for investigating switching feasibility. 

Almost functions were generated by program (and fix by hand). it's not smart but works fine.
I'll improve that codes in a few weeks. It has more than 500 PHP functions. Contributing are welcome! :octocat:

**Comment by chobie** [comment]
@deth4uall probably you can play in March. (you can also play latest libgit2 with `functions` branch. but it doesn't have documents).

I can't promise at this time as wrapping php-git is really tough work. It requires deep knowledge of git internal, libgit2 and PHP internals.
for now, can you play rugged (https://github.com/libgit2/rugged) at first? it's very good reference of OOP with libgit2.
