### ISSUE TITLE
error when trying to make

### ISSUE THREAD

**Issue by onlinecco** [libgit2/php-git#56]
In file included from /var/www/Paomianba/src/repo/php-git/php_git2.h:35,
                 from /var/www/Paomianba/src/repo/php-git/tree.c:25:
/usr/include/php/main/php.h:267: warning: redundant redeclaration of ‘environ’
/usr/include/unistd.h:542: note: previous declaration of ‘environ’ was here
In file included from /usr/include/php/main/php.h:389,
                 from /var/www/Paomianba/src/repo/php-git/php_git2.h:35,
                 from /var/www/Paomianba/src/repo/php-git/tree.c:25:
/usr/include/php/main/php_output.h:49: warning: redundant redeclaration of ‘php_ob_get_buffer’
/usr/include/php/main/php_output.h:40: note: previous declaration of ‘php_ob_get_buffer’ was here
/usr/include/php/main/php_output.h:50: warning: redundant redeclaration of ‘php_ob_get_length’
/usr/include/php/main/php_output.h:41: note: previous declaration of ‘php_ob_get_length’ was here
In file included from /var/www/Paomianba/src/repo/php-git/tree.c:25:
/var/www/Paomianba/src/repo/php-git/php_git2.h: In function ‘create_tree_entry_from_entry’:
/var/www/Paomianba/src/repo/php-git/php_git2.h:270: warning: ISO C90 forbids mixed declarations and code
In file included from /usr/include/php/ext/spl/spl_iterators.h:27,
                 from /usr/include/php/ext/spl/spl_array.h:26,
                 from /var/www/Paomianba/src/repo/php-git/tree.c:26:
/usr/include/php/ext/pcre/php_pcre.h:29:18: error: pcre.h: No such file or directory
In file included from /usr/include/php/ext/spl/spl_iterators.h:27,
                 from /usr/include/php/ext/spl/spl_array.h:26,
                 from /var/www/Paomianba/src/repo/php-git/tree.c:26:
/usr/include/php/ext/pcre/php_pcre.h: At top level:
/usr/include/php/ext/pcre/php_pcre.h:37: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/usr/include/php/ext/pcre/php_pcre.h:38: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/usr/include/php/ext/pcre/php_pcre.h:44: error: expected specifier-qualifier-list before ‘pcre’
make: **\* [tree.lo] Error 1

**Comment by chobie** [comment]
```
/usr/include/php/ext/pcre/php_pcre.h:29:18: error: pcre.h: No such file or directory
```

you should install pcre library before build.
