### ISSUE TITLE
Git\Tree\Entry::toObject() seg fault

### ISSUE THREAD

**Issue by msierks** [libgit2/php-git#6]
I am getting a segmentation fault when calling Git\Tree\Entry::toObject(). It worked correctly before I moved from v0.2.1 tag to develop branch. Also I have libgit v0.11.0 installed.

**Comment by chobie** [comment]
Hi msierks,

thanks your reporting. i'll fix this probrem this weekend.

**Comment by chobie** [comment]
im sorry, this problem cause by my poor typo.

https://github.com/libgit2/php-git/commit/12ddbd766f430988f632f133c5161dee7f3961dc

would you try to check latest php-git?

## 

libgit2 development has become very active. so i think php-git become unstable for a while.

**Comment by msierks** [comment]
cool thanks, that did it.
